FROM node:8

WORKDIR /app

COPY ./ /app/


RUN npm install

RUN mkdir /app/logs


#RUN npm install --global nodemon

#ADD package.json /app/package.json
#RUN npm install
CMD ["ls"]
CMD ["npm","start"]
